from __future__ import annotations


REALTIME_ASR_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Realtime ASR</title>
<style>
:root{--bg:#121314;--top:#0d0e0f;--panel:#1b1d1f;--line:#344044;--text:#e7ecef;--muted:#9facb2;--dim:#66767d;--accent:#55d7ff;--danger:#ffb4ab}
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{background:var(--bg);color:var(--text);font-family:Inter,"Segoe UI",Arial,sans-serif}button,select{font:inherit}.wrap{height:100%;display:grid;grid-template-rows:64px auto 1fr}header{display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:var(--top);border-bottom:1px solid var(--line)}.title{font-size:20px;font-weight:700;text-transform:uppercase}.status{display:flex;align-items:center;gap:10px;color:var(--muted);font:600 12px/1 Consolas,monospace;text-transform:uppercase}.dot{width:8px;height:8px;background:var(--dim)}.dot.live{background:var(--accent);box-shadow:0 0 14px rgba(85,215,255,.7)}.controls{display:grid;grid-template-columns:1fr 150px auto auto auto auto;gap:14px;padding:20px 28px;background:#191b1d;border-bottom:1px solid var(--line)}.field{display:grid;gap:7px}label{color:var(--dim);font:600 12px/1.2 Consolas,monospace;text-transform:uppercase}select{min-height:38px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:0 12px}.btn{min-height:38px;align-self:end;padding:0 18px;border:1px solid var(--line);background:transparent;color:var(--muted);text-transform:uppercase;font:600 12px/1 Consolas,monospace}.btn:hover{background:var(--accent);border-color:var(--accent);color:#001f25}.btn.stop:hover{background:var(--danger);border-color:var(--danger);color:#2a0000}.body{padding:24px 28px;overflow:hidden;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:12px}.panel{border:1px solid var(--line);background:var(--panel);padding:18px;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.panel-head{color:#9ce9ff;font-size:18px;margin-bottom:12px}.text{white-space:pre-wrap;line-height:1.6;font-size:17px;overflow:auto;min-height:0;user-select:text}.partial{color:var(--muted)}.meta{color:var(--dim);font:12px/1.45 Consolas,monospace}.error{color:var(--danger)}
</style></head><body><div class="wrap"><header><div class="title">Realtime ASR</div><div class="status"><span id="dot" class="dot"></span><span id="state">Idle</span></div></header>
<section class="controls"><div class="field"><label for="rt-source">Input Source</label><select id="rt-source"><option value="microphone">Microphone</option><option value="system_audio">System Audio</option><option value="both">Microphone + System</option></select></div><div class="field"><label for="rt-partials">Live Partials</label><select id="rt-partials" onchange="setPartials(this.value)"><option value="off">Off</option><option value="on">On</option></select></div><button class="btn" onclick="startRealtime()">Start</button><button class="btn stop" onclick="stopRealtime()">Stop</button><button class="btn" onclick="clearRealtime()">Clear</button><button class="btn" onclick="saveRealtime()">Save</button></section>
<main class="body"><div class="panel"><div class="panel-head">Live Transcript</div><div id="transcript" class="text"></div></div><div id="meta" class="meta">Model: gpt-realtime-whisper</div><div id="error" class="meta error"></div></main></div>
<script>
let pollTimer=null,selectingText=false;function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function combine(parts){return(parts||[]).filter(Boolean).map(s=>s.replace(/\\s+/g,' ').trim()).join(' ')}
function selectionInside(el){const s=window.getSelection();return!!(s&&!s.isCollapsed&&s.rangeCount&&(el.contains(s.anchorNode)||el.contains(s.focusNode)))}
function renderLiveText(el,html){if(selectingText||selectionInside(el)||el.innerHTML===html)return;el.innerHTML=html;el.scrollTop=el.scrollHeight}
document.addEventListener('pointerdown',e=>{selectingText=!!(e.target instanceof Element&&e.target.closest('.text'))});document.addEventListener('pointerup',()=>{selectingText=false});document.addEventListener('pointercancel',()=>{selectingText=false});
async function startRealtime(){document.getElementById('error').textContent='';const r=await pywebview.api.start_realtime_asr(document.getElementById('rt-source').value);if(!r||r.ok===false){document.getElementById('error').textContent=r&&r.error?r.error:'Unable to start realtime ASR.';return}startPolling()}
async function stopRealtime(){await pywebview.api.stop_realtime_asr();await refreshState()}async function clearRealtime(){await pywebview.api.clear_realtime_asr();await refreshState()}async function saveRealtime(){const r=await pywebview.api.save_realtime_asr();document.getElementById('error').textContent=r&&r.ok?'Saved: '+r.path:(r&&r.error?r.error:'Save failed.')}
async function setPartials(value){await pywebview.api.set_config('realtime.show_partial_words',value==='on');await refreshState()}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(refreshState,250);refreshState()}
async function refreshState(){const s=await pywebview.api.get_realtime_asr_status();document.getElementById('state').textContent=s.status||'Idle';document.getElementById('dot').className=s.running?'dot live':'dot';const finalText=typeof s.text==='string'?s.text:combine(s.finals||[]);const partial=s.partial?'<span class="partial">'+esc(s.partial)+'</span>':'';renderLiveText(document.getElementById('transcript'),esc(finalText)+(finalText&&partial&&!finalText.endsWith('\\n')?' ':'')+partial);document.getElementById('meta').textContent='Provider: '+(s.provider||'openai')+' | Model: '+(s.model||'gpt-realtime-whisper')+' | Source: '+(s.input_mode||'-');document.getElementById('error').textContent=s.error||'';if(!s.running&&pollTimer){clearInterval(pollTimer);pollTimer=null}}
window.addEventListener('pywebviewready',async()=>{const cfg=await pywebview.api.get_config();document.getElementById('rt-source').value=cfg.recorder?.input_mode||'microphone';document.getElementById('rt-partials').value=cfg.realtime?.show_partial_words?'on':'off';startPolling()});
</script></body></html>"""


REALTIME_TRANSLATE_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Realtime Translate</title>
<style>
:root{--bg:#121314;--top:#0d0e0f;--panel:#1b1d1f;--line:#344044;--text:#e7ecef;--muted:#9facb2;--dim:#66767d;--accent:#55d7ff;--danger:#ffb4ab}
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{background:var(--bg);color:var(--text);font-family:Inter,"Segoe UI",Arial,sans-serif}button,select{font:inherit}.wrap{height:100%;display:grid;grid-template-rows:64px auto 1fr}header{display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:var(--top);border-bottom:1px solid var(--line)}.title{font-size:20px;font-weight:700;text-transform:uppercase}.status{display:flex;align-items:center;gap:10px;color:var(--muted);font:600 12px/1 Consolas,monospace;text-transform:uppercase}.dot{width:8px;height:8px;background:var(--dim)}.dot.live{background:var(--accent);box-shadow:0 0 14px rgba(85,215,255,.7)}.controls{display:grid;grid-template-columns:1fr 190px auto auto auto auto;gap:14px;padding:20px 28px;background:#191b1d;border-bottom:1px solid var(--line)}.field{display:grid;gap:7px}label{color:var(--dim);font:600 12px/1.2 Consolas,monospace;text-transform:uppercase}select{min-height:38px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:0 12px}.btn{min-height:38px;align-self:end;padding:0 18px;border:1px solid var(--line);background:transparent;color:var(--muted);text-transform:uppercase;font:600 12px/1 Consolas,monospace}.btn:hover{background:var(--accent);border-color:var(--accent);color:#001f25}.btn.stop:hover{background:var(--danger);border-color:var(--danger);color:#2a0000}.body{padding:24px 28px;overflow:hidden;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:12px}.panel{border:1px solid var(--line);background:var(--panel);padding:18px;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.panel-head{color:#9ce9ff;font-size:18px;margin-bottom:12px}.text{white-space:pre-wrap;line-height:1.6;font-size:17px;overflow:auto;min-height:0;user-select:text}.meta{color:var(--dim);font:12px/1.45 Consolas,monospace}.error{color:var(--danger)}
</style></head><body><div class="wrap"><header><div class="title">Realtime Translate</div><div class="status"><span id="dot" class="dot"></span><span id="state">Idle</span></div></header>
<section class="controls"><div class="field"><label for="rt-source">Input Source</label><select id="rt-source"><option value="microphone">Microphone</option><option value="system_audio">System Audio</option><option value="both">Microphone + System</option></select></div><div class="field"><label for="rt-lang">Target</label><select id="rt-lang"><option value="es">Spanish</option><option value="pt">Portuguese</option><option value="fr">French</option><option value="ja">Japanese</option><option value="ru">Russian</option><option value="zh">Chinese</option><option value="de">German</option><option value="ko">Korean</option><option value="hi">Hindi</option><option value="id">Indonesian</option><option value="vi">Vietnamese</option><option value="it">Italian</option><option value="en">English</option></select></div><button class="btn" onclick="startRealtime()">Start</button><button class="btn stop" onclick="stopRealtime()">Stop</button><button class="btn" onclick="clearRealtime()">Clear</button><button class="btn" onclick="saveRealtime()">Save</button></section>
<main class="body"><div class="panel"><div class="panel-head">Translation</div><div id="translation" class="text"></div></div><div id="meta" class="meta">Model: gpt-realtime-translate</div><div id="error" class="meta error"></div></main></div>
<script>
let pollTimer=null,selectingText=false;function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function selectionInside(el){const s=window.getSelection();return!!(s&&!s.isCollapsed&&s.rangeCount&&(el.contains(s.anchorNode)||el.contains(s.focusNode)))}
function renderLiveText(el,html){if(selectingText||selectionInside(el)||el.innerHTML===html)return;el.innerHTML=html;el.scrollTop=el.scrollHeight}
document.addEventListener('pointerdown',e=>{selectingText=!!(e.target instanceof Element&&e.target.closest('.text'))});document.addEventListener('pointerup',()=>{selectingText=false});document.addEventListener('pointercancel',()=>{selectingText=false});
async function startRealtime(){document.getElementById('error').textContent='';const r=await pywebview.api.start_realtime_translate(document.getElementById('rt-source').value,document.getElementById('rt-lang').value);if(!r||r.ok===false){document.getElementById('error').textContent=r&&r.error?r.error:'Unable to start realtime translation.';return}startPolling()}
async function stopRealtime(){await pywebview.api.stop_realtime_translate();await refreshState()}async function clearRealtime(){await pywebview.api.clear_realtime_translate();await refreshState()}async function saveRealtime(){const r=await pywebview.api.save_realtime_translate();document.getElementById('error').textContent=r&&r.ok?'Saved: '+r.path:(r&&r.error?r.error:'Save failed.')}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(refreshState,250);refreshState()}
async function refreshState(){const s=await pywebview.api.get_realtime_translate_status();document.getElementById('state').textContent=s.status||'Idle';document.getElementById('dot').className=s.running?'dot live':'dot';renderLiveText(document.getElementById('translation'),esc(s.translation_text||''));document.getElementById('meta').textContent='Provider: '+(s.provider||'openai')+' | Model: '+(s.model||'gpt-realtime-translate')+' | Source: '+(s.input_mode||'-')+' | Target: '+(s.target_language||'-');document.getElementById('error').textContent=s.error||'';if(!s.running&&pollTimer){clearInterval(pollTimer);pollTimer=null}}
window.addEventListener('pywebviewready',async()=>{const cfg=await pywebview.api.get_config();document.getElementById('rt-source').value=cfg.recorder?.input_mode||'microphone';document.getElementById('rt-lang').value=cfg.target_language||'zh';startPolling()});
</script></body></html>"""


REALTIME_COMBINED_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Realtime ASR + Translate</title>
<style>
:root{--bg:#121314;--top:#0d0e0f;--panel:#1b1d1f;--line:#344044;--text:#e7ecef;--muted:#9facb2;--dim:#66767d;--accent:#55d7ff;--danger:#ffb4ab}
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{background:var(--bg);color:var(--text);font-family:Inter,"Segoe UI",Arial,sans-serif}button,select{font:inherit}.wrap{height:100%;display:grid;grid-template-rows:64px auto 1fr}header{display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:var(--top);border-bottom:1px solid var(--line)}.title{font-size:20px;font-weight:700;text-transform:uppercase}.status{display:flex;align-items:center;gap:10px;color:var(--muted);font:600 12px/1 Consolas,monospace;text-transform:uppercase}.dot{width:8px;height:8px;background:var(--dim)}.dot.live{background:var(--accent);box-shadow:0 0 14px rgba(85,215,255,.7)}.controls{display:grid;grid-template-columns:1fr 190px auto auto auto auto;gap:14px;padding:20px 28px;background:#191b1d;border-bottom:1px solid var(--line)}.field{display:grid;gap:7px}label{color:var(--dim);font:600 12px/1.2 Consolas,monospace;text-transform:uppercase}select{min-height:38px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:0 12px}.btn{min-height:38px;align-self:end;padding:0 18px;border:1px solid var(--line);background:transparent;color:var(--muted);text-transform:uppercase;font:600 12px/1 Consolas,monospace}.btn:hover{background:var(--accent);border-color:var(--accent);color:#001f25}.btn.stop:hover{background:var(--danger);border-color:var(--danger);color:#2a0000}.body{padding:20px 28px;overflow:hidden;display:grid;grid-template-rows:minmax(0,1fr) minmax(0,1fr) auto;gap:14px}.panel{border:1px solid var(--line);background:var(--panel);padding:16px;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.panel-head{color:#9ce9ff;font-size:17px;margin-bottom:10px}.text{white-space:pre-wrap;line-height:1.55;font-size:16px;overflow:auto;min-height:0;user-select:text}.partial{color:var(--muted)}.meta{color:var(--dim);font:12px/1.45 Consolas,monospace}.error{color:var(--danger)}
</style></head><body><div class="wrap"><header><div class="title">Realtime ASR + Translate</div><div class="status"><span id="dot" class="dot"></span><span id="state">Idle</span></div></header>
<section class="controls"><div class="field"><label for="rt-source">Input Source</label><select id="rt-source"><option value="microphone">Microphone</option><option value="system_audio">System Audio</option><option value="both">Microphone + System</option></select></div><div class="field"><label for="rt-lang">Target</label><select id="rt-lang"><option value="es">Spanish</option><option value="pt">Portuguese</option><option value="fr">French</option><option value="ja">Japanese</option><option value="ru">Russian</option><option value="zh">Chinese</option><option value="de">German</option><option value="ko">Korean</option><option value="hi">Hindi</option><option value="id">Indonesian</option><option value="vi">Vietnamese</option><option value="it">Italian</option><option value="en">English</option></select></div><button class="btn" onclick="startRealtime()">Start</button><button class="btn stop" onclick="stopRealtime()">Stop</button><button class="btn" onclick="clearRealtime()">Clear</button><button class="btn" onclick="saveRealtime()">Save</button></section>
<main class="body"><div class="panel"><div class="panel-head">Live Transcript</div><div id="transcript" class="text"></div></div><div class="panel"><div class="panel-head">Translation</div><div id="translation" class="text"></div></div><div id="meta" class="meta">ASR: gpt-realtime-whisper | Translation: gpt-realtime-translate</div><div id="error" class="meta error"></div></main></div>
<script>
let pollTimer=null,selectingText=false;function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function combine(parts){return(parts||[]).filter(Boolean).map(s=>s.replace(/\\s+/g,' ').trim()).join(' ')}
function selectionInside(el){const s=window.getSelection();return!!(s&&!s.isCollapsed&&s.rangeCount&&(el.contains(s.anchorNode)||el.contains(s.focusNode)))}
function renderLiveText(el,html){if(selectingText||selectionInside(el)||el.innerHTML===html)return;el.innerHTML=html;el.scrollTop=el.scrollHeight}
document.addEventListener('pointerdown',e=>{selectingText=!!(e.target instanceof Element&&e.target.closest('.text'))});document.addEventListener('pointerup',()=>{selectingText=false});document.addEventListener('pointercancel',()=>{selectingText=false});
async function startRealtime(){document.getElementById('error').textContent='';const r=await pywebview.api.start_realtime_combined(document.getElementById('rt-source').value,document.getElementById('rt-lang').value);if(!r||r.ok===false){document.getElementById('error').textContent=r&&r.error?r.error:'Unable to start realtime ASR + translation.';return}startPolling()}
async function stopRealtime(){await pywebview.api.stop_realtime_combined();await refreshState()}async function clearRealtime(){await pywebview.api.clear_realtime_combined();await refreshState()}async function saveRealtime(){const r=await pywebview.api.save_realtime_combined();document.getElementById('error').textContent=r&&r.ok?'Saved: '+r.paths.join(' | '):(r&&r.error?r.error:'Save failed.')}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(refreshState,250);refreshState()}
async function refreshState(){const s=await pywebview.api.get_realtime_combined_status();const running=!!(s.asr?.running||s.translate?.running);document.getElementById('state').textContent=running?'Listening':'Idle';document.getElementById('dot').className=running?'dot live':'dot';const finalText=typeof s.asr?.text==='string'?s.asr.text:combine(s.asr?.finals||[]);const partial=s.asr?.partial?'<span class="partial">'+esc(s.asr.partial)+'</span>':'';renderLiveText(document.getElementById('transcript'),esc(finalText)+(finalText&&partial&&!finalText.endsWith('\\n')?' ':'')+partial);renderLiveText(document.getElementById('translation'),esc(s.translate?.translation_text||''));document.getElementById('meta').textContent='ASR: '+(s.asr?.provider||'openai')+' / '+(s.asr?.model||'gpt-realtime-whisper')+' | Translation: '+(s.translate?.provider||'openai')+' / '+(s.translate?.model||'gpt-realtime-translate')+' | Source: '+(s.asr?.input_mode||s.translate?.input_mode||'-')+' | Target: '+(s.translate?.target_language||'-');document.getElementById('error').textContent=s.error||'';if(!running&&pollTimer){clearInterval(pollTimer);pollTimer=null}}
window.addEventListener('pywebviewready',async()=>{const cfg=await pywebview.api.get_config();document.getElementById('rt-source').value=cfg.recorder?.input_mode||'microphone';document.getElementById('rt-lang').value=cfg.target_language||'zh';startPolling()});
</script></body></html>"""
