from __future__ import annotations


REALTIME_ASR_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Realtime ASR</title>
<style>
:root{--bg:#121314;--top:#0d0e0f;--panel:#1b1d1f;--line:#344044;--text:#e7ecef;--muted:#9facb2;--dim:#66767d;--accent:#55d7ff;--danger:#ffb4ab}
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{background:var(--bg);color:var(--text);font-family:Inter,"Segoe UI",Arial,sans-serif}button,select{font:inherit}.wrap{height:100%;display:grid;grid-template-rows:64px auto 1fr}header{display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:var(--top);border-bottom:1px solid var(--line)}.title{font-size:20px;font-weight:700;text-transform:uppercase}.status{display:flex;align-items:center;gap:10px;color:var(--muted);font:600 12px/1 Consolas,monospace;text-transform:uppercase}.dot{width:8px;height:8px;background:var(--dim)}.dot.live{background:var(--accent);box-shadow:0 0 14px rgba(85,215,255,.7)}.controls{display:grid;grid-template-columns:1fr 150px auto auto auto auto;gap:14px;padding:20px 28px;background:#191b1d;border-bottom:1px solid var(--line)}.field{display:grid;gap:7px}label{color:var(--dim);font:600 12px/1.2 Consolas,monospace;text-transform:uppercase}select{min-height:38px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:0 12px}.btn{min-height:38px;align-self:end;padding:0 18px;border:1px solid var(--line);background:transparent;color:var(--muted);text-transform:uppercase;font:600 12px/1 Consolas,monospace}.btn:hover{background:var(--accent);border-color:var(--accent);color:#001f25}.btn.stop:hover{background:var(--danger);border-color:var(--danger);color:#2a0000}.body{padding:24px 28px;overflow:hidden;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:12px}.panel{border:1px solid var(--line);background:var(--panel);padding:18px;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.panel-head{color:#9ce9ff;font-size:18px;margin-bottom:12px}.text{white-space:pre-wrap;line-height:1.6;font-size:17px;overflow:auto;min-height:0;user-select:text}.partial{color:var(--muted)}.meta{color:var(--dim);font:12px/1.45 Consolas,monospace}.error{color:var(--danger)}
</style></head><body><div class="wrap"><header><div class="title" data-en="Realtime ASR" data-zh="即時語音辨識">Realtime ASR</div><div class="status"><span id="dot" class="dot"></span><span id="state">Idle</span></div></header>
<section class="controls"><div class="field"><label for="rt-source" data-en="Input Source" data-zh="輸入來源">Input Source</label><select id="rt-source"><option value="microphone" data-en="Microphone" data-zh="麥克風">Microphone</option><option value="system_audio" data-en="System Audio" data-zh="系統音訊">System Audio</option><option value="both" data-en="Microphone + System" data-zh="麥克風 + 系統音訊">Microphone + System</option></select></div><div class="field"><label for="rt-partials" data-en="Live Partials" data-zh="即時片段">Live Partials</label><select id="rt-partials" onchange="setPartials(this.value)"><option value="off" data-en="Off" data-zh="關閉">Off</option><option value="on" data-en="On" data-zh="開啟">On</option></select></div><button class="btn" onclick="startRealtime()" data-en="Start" data-zh="開始">Start</button><button class="btn stop" onclick="stopRealtime()" data-en="Stop" data-zh="停止">Stop</button><button class="btn" onclick="clearRealtime()" data-en="Clear" data-zh="清除">Clear</button><button class="btn" onclick="saveRealtime()" data-en="Save" data-zh="儲存">Save</button></section>
<main class="body"><div class="panel"><div class="panel-head" data-en="Live Transcript" data-zh="即時逐字稿">Live Transcript</div><div id="transcript" class="text"></div></div><div id="meta" class="meta">Model: gemini-3.5-live-translate-preview</div><div id="error" class="meta error"></div></main></div>
<script>
let pollTimer=null,selectingText=false,uiLanguage='en';function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function ui(en,zh){return uiLanguage==='zh'?zh:en}function applyLanguage(lang){uiLanguage=lang==='zh'?'zh':'en';document.documentElement.lang=uiLanguage==='zh'?'zh-Hant':'en';document.querySelectorAll('[data-en][data-zh]').forEach(el=>{el.textContent=uiLanguage==='zh'?el.dataset.zh:el.dataset.en})}function statusText(s){if(uiLanguage!=='zh')return s||'Idle';return {'Idle':'閒置','Connecting':'連線中','Listening':'聆聽中','Transcribing':'轉錄中','Error':'錯誤'}[s||'Idle']||s}function combine(parts){return(parts||[]).filter(Boolean).map(s=>s.replace(/\\s+/g,' ').trim()).join(' ')}
function selectionInside(el){const s=window.getSelection();return!!(s&&!s.isCollapsed&&s.rangeCount&&(el.contains(s.anchorNode)||el.contains(s.focusNode)))}
function renderLiveText(el,html){if(selectingText||selectionInside(el)||el.innerHTML===html)return;el.innerHTML=html;el.scrollTop=el.scrollHeight}
document.addEventListener('pointerdown',e=>{selectingText=!!(e.target instanceof Element&&e.target.closest('.text'))});document.addEventListener('pointerup',()=>{selectingText=false});document.addEventListener('pointercancel',()=>{selectingText=false});
async function startRealtime(){document.getElementById('error').textContent='';const r=await pywebview.api.start_realtime_asr(document.getElementById('rt-source').value);if(!r||r.ok===false){document.getElementById('error').textContent=r&&r.error?r.error:ui('Unable to start realtime ASR.','無法啟動即時語音辨識。');return}startPolling()}
async function stopRealtime(){await pywebview.api.stop_realtime_asr();await refreshState()}async function clearRealtime(){await pywebview.api.clear_realtime_asr();await refreshState()}async function saveRealtime(){const r=await pywebview.api.save_realtime_asr();document.getElementById('error').textContent=r&&r.ok?ui('Saved: ','已儲存：')+r.path:(r&&r.error?r.error:ui('Save failed.','儲存失敗。'))}
async function setPartials(value){await pywebview.api.set_config('realtime.show_partial_words',value==='on');await refreshState()}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(refreshState,250);refreshState()}
async function refreshState(){const s=await pywebview.api.get_realtime_asr_status();document.getElementById('state').textContent=statusText(s.status||'Idle');document.getElementById('dot').className=s.running?'dot live':'dot';const finalText=typeof s.text==='string'?s.text:combine(s.finals||[]);const partial=s.partial?'<span class="partial">'+esc(s.partial)+'</span>':'';renderLiveText(document.getElementById('transcript'),esc(finalText)+(finalText&&partial&&!finalText.endsWith('\\n')?' ':'')+partial);document.getElementById('meta').textContent=ui('Provider: ','提供者：')+(s.provider||'gemini')+' | '+ui('Model: ','模型：')+(s.model||'gemini-3.5-live-translate-preview')+' | '+ui('Source: ','來源：')+(s.input_mode||'-');document.getElementById('error').textContent=s.error||'';if(!s.running&&pollTimer){clearInterval(pollTimer);pollTimer=null}}
window.addEventListener('pywebviewready',async()=>{const cfg=await pywebview.api.get_config();applyLanguage(cfg.ui_language||'en');document.getElementById('rt-source').value=cfg.recorder?.input_mode||'microphone';document.getElementById('rt-partials').value=cfg.realtime?.show_partial_words?'on':'off';startPolling()});
</script></body></html>"""


REALTIME_TRANSLATE_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Realtime Translate</title>
<style>
:root{--bg:#121314;--top:#0d0e0f;--panel:#1b1d1f;--line:#344044;--text:#e7ecef;--muted:#9facb2;--dim:#66767d;--accent:#55d7ff;--danger:#ffb4ab}
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{background:var(--bg);color:var(--text);font-family:Inter,"Segoe UI",Arial,sans-serif}button,select{font:inherit}.wrap{height:100%;display:grid;grid-template-rows:64px auto 1fr}header{display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:var(--top);border-bottom:1px solid var(--line)}.title{font-size:20px;font-weight:700;text-transform:uppercase}.status{display:flex;align-items:center;gap:10px;color:var(--muted);font:600 12px/1 Consolas,monospace;text-transform:uppercase}.dot{width:8px;height:8px;background:var(--dim)}.dot.live{background:var(--accent);box-shadow:0 0 14px rgba(85,215,255,.7)}.controls{display:grid;grid-template-columns:1fr 190px auto auto auto auto;gap:14px;padding:20px 28px;background:#191b1d;border-bottom:1px solid var(--line)}.field{display:grid;gap:7px}label{color:var(--dim);font:600 12px/1.2 Consolas,monospace;text-transform:uppercase}select{min-height:38px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:0 12px}.btn{min-height:38px;align-self:end;padding:0 18px;border:1px solid var(--line);background:transparent;color:var(--muted);text-transform:uppercase;font:600 12px/1 Consolas,monospace}.btn:hover{background:var(--accent);border-color:var(--accent);color:#001f25}.btn.stop:hover{background:var(--danger);border-color:var(--danger);color:#2a0000}.body{padding:24px 28px;overflow:hidden;display:grid;grid-template-rows:minmax(0,1fr) auto;gap:12px}.panel{border:1px solid var(--line);background:var(--panel);padding:18px;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.panel-head{color:#9ce9ff;font-size:18px;margin-bottom:12px}.text{white-space:pre-wrap;line-height:1.6;font-size:17px;overflow:auto;min-height:0;user-select:text}.meta{color:var(--dim);font:12px/1.45 Consolas,monospace}.error{color:var(--danger)}
</style></head><body><div class="wrap"><header><div class="title" data-en="Realtime Translate" data-zh="即時翻譯">Realtime Translate</div><div class="status"><span id="dot" class="dot"></span><span id="state">Idle</span></div></header>
<section class="controls"><div class="field"><label for="rt-source" data-en="Input Source" data-zh="輸入來源">Input Source</label><select id="rt-source"><option value="microphone" data-en="Microphone" data-zh="麥克風">Microphone</option><option value="system_audio" data-en="System Audio" data-zh="系統音訊">System Audio</option><option value="both" data-en="Microphone + System" data-zh="麥克風 + 系統音訊">Microphone + System</option></select></div><div class="field"><label for="rt-lang" data-en="Target" data-zh="目標">Target</label><select id="rt-lang"><option value="es" data-en="Spanish" data-zh="西班牙文">Spanish</option><option value="pt" data-en="Portuguese" data-zh="葡萄牙文">Portuguese</option><option value="fr" data-en="French" data-zh="法文">French</option><option value="ja" data-en="Japanese" data-zh="日文">Japanese</option><option value="ru" data-en="Russian" data-zh="俄文">Russian</option><option value="zh" data-en="Chinese" data-zh="中文">Chinese</option><option value="de" data-en="German" data-zh="德文">German</option><option value="ko" data-en="Korean" data-zh="韓文">Korean</option><option value="hi" data-en="Hindi" data-zh="印地文">Hindi</option><option value="id" data-en="Indonesian" data-zh="印尼文">Indonesian</option><option value="vi" data-en="Vietnamese" data-zh="越南文">Vietnamese</option><option value="it" data-en="Italian" data-zh="義大利文">Italian</option><option value="en" data-en="English" data-zh="英文">English</option></select></div><button class="btn" onclick="startRealtime()" data-en="Start" data-zh="開始">Start</button><button class="btn stop" onclick="stopRealtime()" data-en="Stop" data-zh="停止">Stop</button><button class="btn" onclick="clearRealtime()" data-en="Clear" data-zh="清除">Clear</button><button class="btn" onclick="saveRealtime()" data-en="Save" data-zh="儲存">Save</button></section>
<main class="body"><div class="panel"><div class="panel-head" data-en="Translation" data-zh="翻譯">Translation</div><div id="translation" class="text"></div></div><div id="meta" class="meta">Model: gemini-3.5-live-translate-preview</div><div id="error" class="meta error"></div></main></div>
<script>
let pollTimer=null,selectingText=false,uiLanguage='en';function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function ui(en,zh){return uiLanguage==='zh'?zh:en}function applyLanguage(lang){uiLanguage=lang==='zh'?'zh':'en';document.documentElement.lang=uiLanguage==='zh'?'zh-Hant':'en';document.querySelectorAll('[data-en][data-zh]').forEach(el=>{el.textContent=uiLanguage==='zh'?el.dataset.zh:el.dataset.en})}function statusText(s){if(uiLanguage!=='zh')return s||'Idle';return {'Idle':'閒置','Connecting':'連線中','Listening':'聆聽中','Translating':'翻譯中','Error':'錯誤'}[s||'Idle']||s}
function selectionInside(el){const s=window.getSelection();return!!(s&&!s.isCollapsed&&s.rangeCount&&(el.contains(s.anchorNode)||el.contains(s.focusNode)))}
function renderLiveText(el,html){if(selectingText||selectionInside(el)||el.innerHTML===html)return;el.innerHTML=html;el.scrollTop=el.scrollHeight}
document.addEventListener('pointerdown',e=>{selectingText=!!(e.target instanceof Element&&e.target.closest('.text'))});document.addEventListener('pointerup',()=>{selectingText=false});document.addEventListener('pointercancel',()=>{selectingText=false});
async function startRealtime(){document.getElementById('error').textContent='';const r=await pywebview.api.start_realtime_translate(document.getElementById('rt-source').value,document.getElementById('rt-lang').value);if(!r||r.ok===false){document.getElementById('error').textContent=r&&r.error?r.error:ui('Unable to start realtime translation.','無法啟動即時翻譯。');return}startPolling()}
async function stopRealtime(){await pywebview.api.stop_realtime_translate();await refreshState()}async function clearRealtime(){await pywebview.api.clear_realtime_translate();await refreshState()}async function saveRealtime(){const r=await pywebview.api.save_realtime_translate();document.getElementById('error').textContent=r&&r.ok?ui('Saved: ','已儲存：')+r.path:(r&&r.error?r.error:ui('Save failed.','儲存失敗。'))}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(refreshState,250);refreshState()}
async function refreshState(){const s=await pywebview.api.get_realtime_translate_status();document.getElementById('state').textContent=statusText(s.status||'Idle');document.getElementById('dot').className=s.running?'dot live':'dot';renderLiveText(document.getElementById('translation'),esc(s.translation_text||''));document.getElementById('meta').textContent=ui('Provider: ','提供者：')+(s.provider||'gemini')+' | '+ui('Model: ','模型：')+(s.model||'gemini-3.5-live-translate-preview')+' | '+ui('Source: ','來源：')+(s.input_mode||'-')+' | '+ui('Target: ','目標：')+(s.target_language||'-');document.getElementById('error').textContent=s.error||'';if(!s.running&&pollTimer){clearInterval(pollTimer);pollTimer=null}}
window.addEventListener('pywebviewready',async()=>{const cfg=await pywebview.api.get_config();applyLanguage(cfg.ui_language||'en');document.getElementById('rt-source').value=cfg.recorder?.input_mode||'microphone';document.getElementById('rt-lang').value=cfg.target_language||'zh';startPolling()});
</script></body></html>"""


REALTIME_COMBINED_HTML = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Realtime ASR + Translate</title>
<style>
:root{--bg:#121314;--top:#0d0e0f;--panel:#1b1d1f;--line:#344044;--text:#e7ecef;--muted:#9facb2;--dim:#66767d;--accent:#55d7ff;--danger:#ffb4ab}
*{box-sizing:border-box}html,body{height:100%;margin:0;overflow:hidden}body{background:var(--bg);color:var(--text);font-family:Inter,"Segoe UI",Arial,sans-serif}button,select{font:inherit}.wrap{height:100%;display:grid;grid-template-rows:64px auto 1fr}header{display:flex;align-items:center;justify-content:space-between;padding:0 28px;background:var(--top);border-bottom:1px solid var(--line)}.title{font-size:20px;font-weight:700;text-transform:uppercase}.status{display:flex;align-items:center;gap:10px;color:var(--muted);font:600 12px/1 Consolas,monospace;text-transform:uppercase}.dot{width:8px;height:8px;background:var(--dim)}.dot.live{background:var(--accent);box-shadow:0 0 14px rgba(85,215,255,.7)}.controls{display:grid;grid-template-columns:1fr 190px auto auto auto auto;gap:14px;padding:20px 28px;background:#191b1d;border-bottom:1px solid var(--line)}.field{display:grid;gap:7px}label{color:var(--dim);font:600 12px/1.2 Consolas,monospace;text-transform:uppercase}select{min-height:38px;background:var(--panel);color:var(--text);border:1px solid var(--line);padding:0 12px}.btn{min-height:38px;align-self:end;padding:0 18px;border:1px solid var(--line);background:transparent;color:var(--muted);text-transform:uppercase;font:600 12px/1 Consolas,monospace}.btn:hover{background:var(--accent);border-color:var(--accent);color:#001f25}.btn.stop:hover{background:var(--danger);border-color:var(--danger);color:#2a0000}.body{padding:20px 28px;overflow:hidden;display:grid;grid-template-rows:minmax(0,1fr) minmax(0,1fr) auto;gap:14px}.panel{border:1px solid var(--line);background:var(--panel);padding:16px;min-height:0;display:grid;grid-template-rows:auto minmax(0,1fr)}.panel-head{color:#9ce9ff;font-size:17px;margin-bottom:10px}.text{white-space:pre-wrap;line-height:1.55;font-size:16px;overflow:auto;min-height:0;user-select:text}.partial{color:var(--muted)}.meta{color:var(--dim);font:12px/1.45 Consolas,monospace}.error{color:var(--danger)}
</style></head><body><div class="wrap"><header><div class="title" data-en="Realtime ASR + Translate" data-zh="即時語音辨識 + 翻譯">Realtime ASR + Translate</div><div class="status"><span id="dot" class="dot"></span><span id="state">Idle</span></div></header>
<section class="controls"><div class="field"><label for="rt-source" data-en="Input Source" data-zh="輸入來源">Input Source</label><select id="rt-source"><option value="microphone" data-en="Microphone" data-zh="麥克風">Microphone</option><option value="system_audio" data-en="System Audio" data-zh="系統音訊">System Audio</option><option value="both" data-en="Microphone + System" data-zh="麥克風 + 系統音訊">Microphone + System</option></select></div><div class="field"><label for="rt-lang" data-en="Target" data-zh="目標">Target</label><select id="rt-lang"><option value="es" data-en="Spanish" data-zh="西班牙文">Spanish</option><option value="pt" data-en="Portuguese" data-zh="葡萄牙文">Portuguese</option><option value="fr" data-en="French" data-zh="法文">French</option><option value="ja" data-en="Japanese" data-zh="日文">Japanese</option><option value="ru" data-en="Russian" data-zh="俄文">Russian</option><option value="zh" data-en="Chinese" data-zh="中文">Chinese</option><option value="de" data-en="German" data-zh="德文">German</option><option value="ko" data-en="Korean" data-zh="韓文">Korean</option><option value="hi" data-en="Hindi" data-zh="印地文">Hindi</option><option value="id" data-en="Indonesian" data-zh="印尼文">Indonesian</option><option value="vi" data-en="Vietnamese" data-zh="越南文">Vietnamese</option><option value="it" data-en="Italian" data-zh="義大利文">Italian</option><option value="en" data-en="English" data-zh="英文">English</option></select></div><button class="btn" onclick="startRealtime()" data-en="Start" data-zh="開始">Start</button><button class="btn stop" onclick="stopRealtime()" data-en="Stop" data-zh="停止">Stop</button><button class="btn" onclick="clearRealtime()" data-en="Clear" data-zh="清除">Clear</button><button class="btn" onclick="saveRealtime()" data-en="Save" data-zh="儲存">Save</button></section>
<main class="body"><div class="panel"><div class="panel-head" data-en="Live Transcript" data-zh="即時逐字稿">Live Transcript</div><div id="transcript" class="text"></div></div><div class="panel"><div class="panel-head" data-en="Translation" data-zh="翻譯">Translation</div><div id="translation" class="text"></div></div><div id="meta" class="meta">ASR: gemini-3.5-live-translate-preview | Translation: gemini-3.5-live-translate-preview</div><div id="error" class="meta error"></div></main></div>
<script>
let pollTimer=null,selectingText=false,uiLanguage='en';function esc(s){return(s||'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}function ui(en,zh){return uiLanguage==='zh'?zh:en}function applyLanguage(lang){uiLanguage=lang==='zh'?'zh':'en';document.documentElement.lang=uiLanguage==='zh'?'zh-Hant':'en';document.querySelectorAll('[data-en][data-zh]').forEach(el=>{el.textContent=uiLanguage==='zh'?el.dataset.zh:el.dataset.en})}function statusText(s){if(uiLanguage!=='zh')return s||'Idle';return {'Idle':'閒置','Listening':'聆聽中','Connecting':'連線中','Transcribing':'轉錄中','Translating':'翻譯中','Error':'錯誤'}[s||'Idle']||s}function combine(parts){return(parts||[]).filter(Boolean).map(s=>s.replace(/\\s+/g,' ').trim()).join(' ')}
function selectionInside(el){const s=window.getSelection();return!!(s&&!s.isCollapsed&&s.rangeCount&&(el.contains(s.anchorNode)||el.contains(s.focusNode)))}
function renderLiveText(el,html){if(selectingText||selectionInside(el)||el.innerHTML===html)return;el.innerHTML=html;el.scrollTop=el.scrollHeight}
document.addEventListener('pointerdown',e=>{selectingText=!!(e.target instanceof Element&&e.target.closest('.text'))});document.addEventListener('pointerup',()=>{selectingText=false});document.addEventListener('pointercancel',()=>{selectingText=false});
async function startRealtime(){document.getElementById('error').textContent='';const r=await pywebview.api.start_realtime_combined(document.getElementById('rt-source').value,document.getElementById('rt-lang').value);if(!r||r.ok===false){document.getElementById('error').textContent=r&&r.error?r.error:ui('Unable to start realtime ASR + translation.','無法啟動即時語音辨識 + 翻譯。');return}startPolling()}
async function stopRealtime(){await pywebview.api.stop_realtime_combined();await refreshState()}async function clearRealtime(){await pywebview.api.clear_realtime_combined();await refreshState()}async function saveRealtime(){const r=await pywebview.api.save_realtime_combined();document.getElementById('error').textContent=r&&r.ok?ui('Saved: ','已儲存：')+r.paths.join(' | '):(r&&r.error?r.error:ui('Save failed.','儲存失敗。'))}
function startPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=setInterval(refreshState,250);refreshState()}
async function refreshState(){const s=await pywebview.api.get_realtime_combined_status();const running=!!(s.asr?.running||s.translate?.running);document.getElementById('state').textContent=statusText(running?'Listening':'Idle');document.getElementById('dot').className=running?'dot live':'dot';const finalText=typeof s.asr?.text==='string'?s.asr.text:combine(s.asr?.finals||[]);const partial=s.asr?.partial?'<span class="partial">'+esc(s.asr.partial)+'</span>':'';renderLiveText(document.getElementById('transcript'),esc(finalText)+(finalText&&partial&&!finalText.endsWith('\\n')?' ':'')+partial);renderLiveText(document.getElementById('translation'),esc(s.translate?.translation_text||''));document.getElementById('meta').textContent='ASR: '+(s.asr?.provider||'gemini')+' / '+(s.asr?.model||'gemini-3.5-live-translate-preview')+' | '+ui('Translation: ','翻譯：')+(s.translate?.provider||'gemini')+' / '+(s.translate?.model||'gemini-3.5-live-translate-preview')+' | '+ui('Source: ','來源：')+(s.asr?.input_mode||s.translate?.input_mode||'-')+' | '+ui('Target: ','目標：')+(s.translate?.target_language||'-');document.getElementById('error').textContent=s.error||'';if(!running&&pollTimer){clearInterval(pollTimer);pollTimer=null}}
window.addEventListener('pywebviewready',async()=>{const cfg=await pywebview.api.get_config();applyLanguage(cfg.ui_language||'en');document.getElementById('rt-source').value=cfg.recorder?.input_mode||'microphone';document.getElementById('rt-lang').value=cfg.target_language||'zh';startPolling()});
</script></body></html>"""
